services:
  django-app:
    #build:
    #  context: .  # Path to your Django project
    image: user_monitoring-django-app:latest  # Use the latest image built
    container_name: unique-django-app  # Unique container name for Django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"  # Expose Django app to localhost:8000
    volumes:
      - .:/app  # Mount your project directory
    depends_on:
      - postgres-db
    networks:
      - custom_monitor_network

  postgres-db:
    image: postgres
    container_name: unique-postgres-db  # Unique container name for PostgreSQL
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: imfreaked@008
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Expose PostgreSQL to localhost:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - custom_monitor_network

networks:
  custom_monitor_network:
    driver: bridge

volumes:
  postgres_data:
