# Generated by Django 5.1.1 on 2024-10-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("read_bible", models.BooleanField(default=False)),
                ("prayed", models.BooleanField(default=False)),
                ("exercised", models.BooleanField(default=False)),
                ("satisfied", models.BooleanField(default=False)),
                ("hurt_someone", models.BooleanField(default=False)),
                ("loved_someone", models.CharField(max_length=100)),
                ("daily_summary", models.TextField(max_length=500)),
            ],
        ),
    ]
