# Generated by Django 5.1.1 on 2024-10-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_rename_exercised_userinput_book_reading_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinput",
            old_name="prayed_for_world_peace",
            new_name="prayer_god",
        ),
    ]
