# Generated by Django 5.1.1 on 2024-10-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0003_rename_prayed_for_world_peace_userinput_prayer_god"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinput",
            old_name="masturbated",
            new_name="maintained_purity",
        ),
    ]
