# Generated by Django 4.1.13 on 2024-12-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0004_rename_masturbated_userinput_maintained_purity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=3000)),
            ],
        ),
    ]
