# Generated by Django 5.1.4 on 2024-12-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0005_quote"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=255)),
                ("task_type", models.CharField(default="normal", max_length=50)),
                ("priority", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TodoTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
