# Generated by Django 5.1.4 on 2024-12-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0006_calendartask_todotask"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todotask",
            old_name="name",
            new_name="task_name",
        ),
        migrations.AlterField(
            model_name="calendartask",
            name="priority",
            field=models.CharField(
                choices=[
                    ("high", "Highly Important"),
                    ("medium", "Medium Important"),
                    ("important", "Important"),
                ],
                default="important",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="calendartask",
            name="task_type",
            field=models.CharField(
                choices=[("normal", "Normal"), ("day", "Day")], max_length=50
            ),
        ),
    ]
