# Generated by Django 5.1.4 on 2025-01-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0007_rename_name_todotask_task_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinput",
            name="daily_summary",
            field=models.TextField(
                help_text="A short summary of your day.", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="userinput",
            name="loved_someone",
            field=models.CharField(
                help_text="Name of someone you loved today.", max_length=100
            ),
        ),
    ]
